### ISSUE TITLE
Why is WebRequest a typeclass?

### ISSUE THREAD

**Issue by pjrt** [pikajude/hs-airbrake#2]
It seems like it wants to be a Data type. In fact, I don't see why it should be a class at all. All it does is force users to make orphan instances for non wai requests (ie: Snap). 

Why not just make a Data type that has all of the field the class has, and then have a function that converts a wai-request to a `WebRequest`? 

Then people can make simple functions from their frameworks' requests to a `WebRequest` (ie: `SomeRequest -> WebRequest`).

**Comment by pikajude** [comment]
Sure, this sounds like a good idea.

**Comment by pikajude** [comment]
26727ca819bafa5a46937b400e133c3216d5acab should have fixed this. Let me know if anything looks wrong.

**Comment by pjrt** [comment]
Look great, though would have been better if the whitespace change and modernization was done in a different commit. 

But great, I can now remove my own `WebRequest` data-type. Thx!
